site_name: YAGUI docs
site_description: "Documentation for ComputerCraft's YAGUI library made by hds536jhmk : https://github.com/hds536jhmk/YAGUI/"
repo_url: https://github.com/hds536jhmk/YAGUI/
site_author: hds536jhmk
copyright: Copyright (c) 2019, hds536jhmk
nav:
    - Introduction: Introduction/index.md
    - About: About/LICENSE.md
    - Modules:
      - Introduction: Modules/index.md
      - info: Modules/info_module.md
      - Constants: Modules/constants.md
      - generic_utils: Modules/generic_utils_module.md
      - string_utils: Modules/string_utils_module.md
theme: readthedocs
extra:
  version: 0.4