site_name: YAGUI's Documentation
site_description: "Documentation for ComputerCraft's YAGUI library made by Marco4413 : https://github.com/Marco4413/YAGUI/"
repo_url: https://github.com/Marco4413/YAGUI/
site_author: Marco4413
copyright: Copyright (c) 2022, Marco4413
nav:
    - Introduction: index.md
    - About: About/LICENSE.md
    - Modules:
      - Introduction: Modules/index.md
      - info: Modules/info_module.md
      - Constants: Modules/constants.md
      - generic_utils: Modules/generic_utils_module.md
      - string_utils: Modules/string_utils_module.md
      - math_utils:
        - General: Modules/math_utils_module.md
        - Vectors: Modules/Vectors.md
      - table_utils: Modules/table_utils_module.md
theme:
  name: darkly
  highlightjs: true
  hljs_languages:
      - lua
  navigation_depth: 4
extra_css: [style.css]
